DROP TABLE IF EXISTS project;

DROP TABLE IF EXISTS site;

CREATE TABLE IF NOT EXISTS project (
	id bigint generated by default as identity,
	created_by varchar(255),
	created_date timestamp,
	modified_by varchar(255),
	modified_date timestamp,
	version bigint,
	lead_first_name varchar(255),
	lead_last_name varchar(255),
	name varchar(255),
	primary key(id)
);

CREATE TABLE IF NOT EXISTS site (
	id bigint generated by default as identity,
	created_by varchar(255),
	created_date timestamp,
	modified_by varchar(255),
	modified_date timestamp,
	version bigint,
	address varchar(255),
	city varchar(255),
	name varchar(255),
	state varchar(255),
	zipcode varchar(255),
	primary key(id)
);

INSERT INTO project
	(id, created_by, created_date, modified_by, modified_date, version, 
	lead_first_name, lead_last_name, name)
VALUES 
	(1, null, null, null, null, 0,
	'John', 'Doe', 'The Humane Society');

INSERT INTO project
	(id, created_by, created_date, modified_by, modified_date, version, 
	lead_first_name, lead_last_name, name)
VALUES 
	(2, null, null, null, null, 0,
	'Dhruval', 'Patel', 'Pencils of Promise');

INSERT INTO project
	(id, created_by, created_date, modified_by, modified_date, version, 
	lead_first_name, lead_last_name, name)
VALUES 
	(3, null, null, null, null, 0,
	'Sam', 'Rubin', 'Make-A-Wish Foundation');

INSERT INTO project
	(id, created_by, created_date, modified_by, modified_date, version, 
	lead_first_name, lead_last_name, name)
VALUES 
	(4, null, null, null, null, 0,
	'Chloe', 'Lockard', 'Armed Services YMCA');

INSERT INTO project
	(id, created_by, created_date, modified_by, modified_date, version, 
	lead_first_name, lead_last_name, name)
VALUES 
	(5, null, null, null, null, 0,
	'Jason', 'Louth', 'American Cancer Society');

INSERT INTO project
	(id, created_by, created_date, modified_by, modified_date, version, 
	lead_first_name, lead_last_name, name)
VALUES 
	(6, null, null, null, null, 0,
	'Andrew', 'Felix', 'Charity: Water');
