DROP TABLE IF EXISTS project;

DROP TABLE IF EXISTS site;

CREATE TABLE IF NOT EXISTS project (
	id bigint generated by default as identity,
	created_by varchar(255),
	created_date timestamp,
	modified_by varchar(255),
	modified_date timestamp,
	version bigint,
	lead_first_name varchar(255),
	lead_last_name varchar(255),
	name varchar(255),
	primary key(id)
);

CREATE TABLE IF NOT EXISTS site (
	id bigint generated by default as identity,
	created_by varchar(255),
	created_date timestamp,
	modified_by varchar(255),
	modified_date timestamp,
	version bigint,
	address varchar(255),
	city varchar(255),
	name varchar(255),
	state varchar(255),
	zipcode varchar(255),
	primary key(id)
);

INSERT INTO project
	(id, created_by, created_date, modified_by, modified_date, version, 
	lead_first_name, lead_last_name, name)
VALUES 
	(1, null, null, null, null, 0,
	'John', 'Doe', 'The Humane Society');

INSERT INTO project
	(id, created_by, created_date, modified_by, modified_date, version, 
	lead_first_name, lead_last_name, name)
VALUES 
	(2, null, null, null, null, 0,
	'Dhruval', 'Patel', 'Pencils of Promise');

INSERT INTO project
	(id, created_by, created_date, modified_by, modified_date, version, 
	lead_first_name, lead_last_name, name)
VALUES 
	(3, null, null, null, null, 0,
	'Sam', 'Rubin', 'Make-A-Wish Foundation');

INSERT INTO project
	(id, created_by, created_date, modified_by, modified_date, version, 
	lead_first_name, lead_last_name, name)
VALUES 
	(4, null, null, null, null, 0,
	'Chloe', 'Lockard', 'Armed Services YMCA');

INSERT INTO project
	(id, created_by, created_date, modified_by, modified_date, version, 
	lead_first_name, lead_last_name, name)
VALUES 
	(5, null, null, null, null, 0,
	'Jason', 'Louth', 'American Cancer Society');

INSERT INTO project
	(id, created_by, created_date, modified_by, modified_date, version, 
	lead_first_name, lead_last_name, name)
VALUES 
	(6, null, null, null, null, 0,
	'Andrew', 'Felix', 'Charity: Water');

INSERT INTO site
	(id, created_by, created_date, modified_by, modified_date, version,
	name, address, city, state, zipcode)
VALUES
	(1, null, null, null, null, 0,
	'Site 1', '123 ABC Lane', 'Annapolis Junction', 'MD', '12345');
	
INSERT INTO site
	(id, created_by, created_date, modified_by, modified_date, version,
	name, address, city, state, zipcode)
VALUES
	(2, null, null, null, null, 0,
	'Site 2', '234 DEF Road', 'Jessup', 'MD', '23456');
	
INSERT INTO site
	(id, created_by, created_date, modified_by, modified_date, version,
	name, address, city, state, zipcode)
VALUES
	(3, null, null, null, null, 0,
	'Site 3', '345 GHI Blvd', 'Laurel', 'MD', '34567');
	
INSERT INTO site
	(id, created_by, created_date, modified_by, modified_date, version,
	name, address, city, state, zipcode)
VALUES
	(4, null, null, null, null, 0,
	'Site 4', '456 JKL Road', 'Annapolis Junction', 'MD', '45678');
	
INSERT INTO site
	(id, created_by, created_date, modified_by, modified_date, version,
	name, address, city, state, zipcode)
VALUES
	(5, null, null, null, null, 0,
	'Site 5', '567 MNO Blvd', 'Jessup', 'MD', '56789');
	
INSERT INTO site
	(id, created_by, created_date, modified_by, modified_date, version,
	name, address, city, state, zipcode)
VALUES
	(6, null, null, null, null, 0,
	'Site 6', '678 PQR Lane', 'Laurel', 'MD', '67890');